export const DI_TYPES = {
  DataSource: Symbol.for("DataSource"),
  BuildingsRepository: Symbol.for("BuildingsRepository"),
  BuildingsService: Symbol.for("BuildingsService"),
  BuildingsController: Symbol.for("BuildingsController"),
  CostCenterRepository: Symbol.for("CostCenterRepository"),

  AccountRepository: Symbol.for("AccountRepository"),
  AccountAssemblyRepository: Symbol.for("AccountAssemblyRepository"),
  AccountDistributiveRepository: Symbol.for("AccountDistributiveRepository"),
  AccountService: Symbol.for("AccountService"),
  AccountController: Symbol.for("AccountController"),

  ReservationPropertyRepository: Symbol.for("ReservationPropertyRepository"),
  ReservationPropertyService: Symbol.for("ReservationPropertyService"),
  ReservationPropertyController: Symbol.for("ReservationPropertyController"),

  ApartmentRepository: Symbol.for("ApartmentRepository"),
  ApartmentService: Symbol.for("ApartmentService"),
  ApartmentController: Symbol.for("ApartmentController"),
  ApartmentPicturesRepository: Symbol.for("ApartmentPicturesRepository"),
  ApartmentRentalPriceRepository: Symbol.for("ApartmentRentalPriceRepository"),
  ApartmentSellingPriceRepository: Symbol.for(
    "ApartmentSellingPriceRepository"
  ),
  ApartmentAccumulateRepository: Symbol.for("ApartmentAccumulateRepository"),

  ShopRepository: Symbol.for('ShopRepository'),
  ShopService: Symbol.for('ShopService'),
  ShopController: Symbol.for('ShopController'),
  ShopPicturesRepository: Symbol.for('ShopPicturesRepository'),
  ShopRentalPriceRepository: Symbol.for('ShopRentalPriceRepository'),
  ShopSellingPriceRepository: Symbol.for('ShopSellingPriceRepository'),
  ShopAccumulateRepository: Symbol.for('ShopAccumulateRepository'),
  ShopFixedAssetsRepository: Symbol.for('ShopFixedAssetsRepository'),

  ParkingRepository: Symbol.for('ParkingRepository'),
  ParkingPicturesRepository: Symbol.for('ParkingPicturesRepository'),
  ParkingAccumulateRepository: Symbol.for('ParkingAccumulateRepository'),
  ParkingRentalPriceRepository: Symbol.for('ParkingRentalPriceRepository'),
  ParkingSellingPriceRepository: Symbol.for('ParkingSellingPriceRepository'),
  ParkingWalletRepository: Symbol.for('ParkingWalletRepository'),
  ParkingService: Symbol.for('ParkingService'),
  ParkingController: Symbol.for('ParkingController'),

  LandRepository: Symbol.for('LandRepository'),
  LandRentalPriceRepository: Symbol.for('LandRentalPriceRepository'),
  LandSellingPriceRepository: Symbol.for('LandSellingPriceRepository'),
  LandAccumulateRepository: Symbol.for('LandAccumulateRepository'),
  LandWalletRepository: Symbol.for('LandWalletRepository'),
  LandService: Symbol.for('LandService'),
  LandController: Symbol.for('LandController'),

  VillaRepository: Symbol.for('VillaRepository'),
  VillaRentalPriceRepository: Symbol.for('VillaRentalPriceRepository'),
  VillaSellingPriceRepository: Symbol.for('VillaSellingPriceRepository'),
  VillaService: Symbol.for('VillaService'),
  VillaController: Symbol.for('VillaController'),

  OwnerRepository: Symbol.for('OwnerRepository'),
  OwnerExpensesRepository: Symbol.for('OwnerExpensesRepository'),
  OwnerExpensesDetailsRepository: Symbol.for('OwnerExpensesDetailsRepository'),
  OwnerExpensesTypesRepository: Symbol.for('OwnerExpensesTypesRepository'),
  OwnerService: Symbol.for('OwnerService'),
  OwnerController: Symbol.for('OwnerController'),

  BankRepository: Symbol.for('BankRepository'),
  BankService: Symbol.for('BankService'),
  BankController: Symbol.for('BankController'),


  CurrencyRepository: Symbol.for("CurrencyRepository"),
  CurrencyService: Symbol.for("CurrencyService"),
  CurrencyController: Symbol.for("CurrencyController"),

  LessorRepository: Symbol.for("LessorRepository"),
  LessorService: Symbol.for("LessorService"),
  LessorController: Symbol.for("LessorController"),

  SellerRepository: Symbol.for("SellerRepository"),
  SellerService: Symbol.for("SellerService"),
  SellerController: Symbol.for("SellerController"),

  PropertyValuesRepository: Symbol.for("PropertyValuesRepository"),

  ChequePatternRepository: Symbol.for('ChequePatternRepository'),
  ContractPatternRepository: Symbol.for('ContractPatternRepository'),
  BillPatternRepository: Symbol.for('BillPatternRepository'),
  VoucherPatternRepository: Symbol.for('VoucherPatternRepository'),
  AccountingVoucherPatternRepository: Symbol.for('AccountingVoucherPatternRepository'),
  PatternService: Symbol.for('PatternService'),
  PatternController: Symbol.for('PatternController'),

  MaterialRepository: Symbol.for("MaterialRepository"),
  MaterialGroupRepository: Symbol.for("MaterialGroupRepository"),
  MaterialBalanceRepository: Symbol.for("MaterialBalanceRepository"),
  MaterialMinimumRepository: Symbol.for("MaterialMinimumRepository"),
  MaterialPricesRepository: Symbol.for("MaterialPricesRepository"),
  MaterialPricesDetailsRepository: Symbol.for("MaterialPricesDetailsRepository"),
  MaterialSpecificationsRepository: Symbol.for("MaterialSpecificationsRepository"),
  MaterialService: Symbol.for("MaterialService"),
  MaterialController: Symbol.for("MaterialController"),

  EntryMainDataRepository: Symbol.for('EntryMainDataRepository'),
  EntryGridDataRepository: Symbol.for('EntryGridDataRepository'),
  EntriesController: Symbol.for('EntriesController'),
  EntriesService: Symbol.for('EntriesService'),

  VoucherMainDataRepository: Symbol.for('VoucherMainDataRepository'),
  VoucherGridDataRepository: Symbol.for('VoucherGridDataRepository'),
  VoucherPicturesRepository: Symbol.for('VoucherPicturesRepository'),
  VoucherService: Symbol.for('VoucherService'),
  VoucherController: Symbol.for('VoucherController'),

  ChequeRepository: Symbol.for('ChequeRepository'),
  ChequeService: Symbol.for('ChequeService'),
  ChequeController: Symbol.for('ChequeController'),

  ChequeEntryService: Symbol.for('ChequeEntryService'),
  TerminationEntryService: Symbol.for('TerminationEntryService'),
  TerminationFinesEntryService: Symbol.for('TerminationFinesEntryService'),
  FeesEntryService: Symbol.for('FeesEntryService'),
  ContractEntryService: Symbol.for('ContractEntryService'),
  VoucherEntryService: Symbol.for('VoucherEntryService'),
  EntryGenerationFacade: Symbol.for('EntryGenerationFacade'),
  BillEntryService: Symbol.for('BillEntryService'),

  OpCollectionRepository: Symbol.for('OpCollectionRepository'),
  OpReturnRepository: Symbol.for('OpReturnRepository'),
  OpDeportationRepository: Symbol.for('OpDeportationRepository'),
  OpPartialCollectionRepository: Symbol.for('OpPartialCollectionRepository'),
  OpService: Symbol.for('OpService'),
  OpController: Symbol.for('OpController'),

  ContractRepository: Symbol.for('ContractRepository'),
  ContractTermsRepository: Symbol.for('ContractTermsRepository'),
  ContractPicturesRepository: Symbol.for('ContractPicturesRepository'),
  ContractCommissionRepository: Symbol.for('ContractCommissionRepository'),
  ContractCycleRepository: Symbol.for('ContractCycleRepository'),
  ContractFeeRepository: Symbol.for('ContractFeeRepository'),
  ContractOtherFeesRepository: Symbol.for('ContractOtherFeesRepository'),
  ContractTerminationRepository: Symbol.for('ContractTerminationRepository'),
  InstallmentRepository: Symbol.for('InstallmentRepository'),
  ContractService: Symbol.for('ContractService'),
  ContractController: Symbol.for('ContractController'),

  BillRepository: Symbol.for('BillRepository'),
  BillMaterialDetailsRepository: Symbol.for('BillMaterialDetailsRepository'),
  BillDiscountsDetailsRepository: Symbol.for('BillDiscountsDetailsRepository'),
  BillService: Symbol.for('BillService'),
  BillController: Symbol.for('BillController')
};
